const fs = require('fs');
let b = fs.readFileSync('d:/newproject/_wiki_fetch2.json');
let s;
if (b[0] === 0xFF && b[1] === 0xFE) s = b.slice(2).toString('utf16le');
else if (b[0] === 0xEF && b[1] === 0xBB && b[2] === 0xBF) s = b.slice(3).toString('utf8');
else s = b.toString('utf8');
const j = JSON.parse(s);
const c = j.data.document.content;
const i = c.indexOf('最终效果');
console.log('idx of 最终效果 =', i);
console.log('ctx before:', c.slice(i - 400, i + 60));
console.log('---- search 06 / 05 / 偏远 ----');
console.log('has 05 row text:', c.includes('提交订单前校验偏远地区'));
console.log('all tbody ids near 功能清单:');
const re = /<tbody id="([^"]+)">/g; let m; const ids = [];
while ((m = re.exec(c))) ids.push(m[1]);
console.log(ids.join('\n'));
