const fs = require('fs');
let b = fs.readFileSync('d:/newproject/_wiki_fetch.json');
let s;
if (b[0] === 0xFF && b[1] === 0xFE) s = b.slice(2).toString('utf16le');
else if (b[0] === 0xEF && b[1] === 0xBB && b[2] === 0xBF) s = b.slice(3).toString('utf8');
else s = b.toString('utf8');
const j = JSON.parse(s);
console.log('top keys:', Object.keys(j));
console.log('data keys:', Object.keys(j.data));
console.log('document keys:', Object.keys(j.data.document));
const d = j.data.document;
console.log('token=', d.token, '| id=', d.id, '| doc_id=', d.doc_id, '| url=', d.url);
console.log('JSON keys in document:', Object.keys(d));
