const fs = require('fs');
let b = fs.readFileSync('d:/newproject/_wiki_fetch2.json');
let s;
if (b[0] === 0xFF && b[1] === 0xFE) s = b.slice(2).toString('utf16le');
else if (b[0] === 0xEF && b[1] === 0xBB && b[2] === 0xBF) s = b.slice(3).toString('utf8');
else s = b.toString('utf8');
const j = JSON.parse(s);
const c = j.data.document.content;
console.log('fetch ok:', j.ok);
console.log('has 06 row:', c.includes('doxcnAdd06a'));
console.log('has 验收支付宝行:', c.includes('线上充值-微信浏览器支付宝拦截'));
console.log('content len:', c.length);
